<robot name="camera" xmlns:xacro="http://wiki.ros.org/xacro">
<!-- creater camera-->
<!-- 1.parameters -->
<xacro:property name="camera_x" value="0.02" />
<xacro:property name="camera_y" value="0.05" />
<xacro:property name="camera_z" value="0.03" />
<xacro:property name="camera_mass" value="0.01"/>
<xacro:property name="joint_camera_x" value="${body_length/2-camera_x}" />
<xacro:property name="joint_camera_y" value="0" />
<xacro:property name="joint_camera_z" value="${body_height/2+camera_z/2}" />

<!-- link and joint -->
<link name="camera">
        <visual>
                <geometry>
                        <box size="${camera_x} ${camera_y} ${camera_z}"/>
                </geometry>

                <material name="black">
                        <color rgba="0 0 0 0.8"/>
                </material>

        </visual>
        <collision>
                <geometry>
                        <box size="${camera_x} ${camera_y} ${camera_z}"/>
                </geometry>
        </collision>
        <xacro:Box_inertial_matrix m="${camera_mass}" l="${camera_x}" w="${camera_y}" h="${camera_z}"/>
</link>

<joint name="camera2body" type="fixed">
        <parent link="body"/>
        <child link="camera"/>
        <origin xyz="${joint_camera_x} ${joint_camera_y} ${joint_camera_z}" rpy="0 0 0"/>
</joint>

<gazebo reference="camera">
        <material>Gazebo/Blue</material>
</gazebo>

</robot>