<robot name="laser" xmlns:xacro="http://wiki.ros.org/xacro">
<!-- laser -->
<!-- parameter s-->
<xacro:property name="support_radius" value="0.01"/>
<xacro:property name="support_length" value="0.15"/>
<xacro:property name="laser_radius" value="0.03"/>
<xacro:property name="laser_length" value="0.05"/>
<xacro:property name="support_mass" value="0.02"/>
<xacro:property name="laser_mass" value="0.1"/>

<xacro:property name="joint_support_x" value="0"/>
<xacro:property name="joint_support_y" value="0"/>
<xacro:property name="joint_support_z" value="${support_length/2+body_height/2}"/>
<xacro:property name="joint_laser_z" value="${support_length/2+laser_length/2}"/>

<link name="support" >
        <visual>
                <geometry>
                        <cylinder radius="${support_radius}" length="${support_length}"/>
                </geometry>
                <material name="red">
                        <color rgba="0.9 0.1 0.1 0.8"/>
                </material>
        </visual>
        <collision>
                   <geometry>
                        <cylinder radius="${support_radius}" length="${support_length}"/>
                </geometry>
        </collision>
        <xacro:cylinder_inertial_matrix r="${support_radius}" m="${support_mass}" h="${support_length}"/>
</link>

<link name="laser" >
        <visual>
                <geometry>
                        <cylinder radius="${laser_radius}" length="${laser_length}"/>
                </geometry>
                <material name="black"/>
        </visual>
          <collision>
                    <geometry>
                        <cylinder radius="${laser_radius}" length="${laser_length}"/>
                </geometry>
        </collision>
        <xacro:cylinder_inertial_matrix r="${laser_radius}" m="${laser_mass}" h="${laser_length}"/>
</link>

<!-- joint -->

<joint name="support2body" type="fixed">
        <parent link="body"/>
        <child link="support"/>
        <origin xyz="0 0 ${joint_support_z}" rpy="0 0 0"/>
</joint>

<joint name="laser2support" type="fixed">
        <parent link="support"/>
        <child link = "laser"/>
        <origin xyz="0 0 ${joint_laser_z}" rpy="0 0 0"/>
        </joint>

        <gazebo reference="support">
                <material>Gazebo/White</material>
        </gazebo>

          <gazebo reference="laser">
                <material>Gazebo/Black</material>
        </gazebo>
</robot>